teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.5
    scale_linear_turbo:
      x: 2.0

    axis_angular:
      yaw: 3
    scale_angular:
      yaw: 1.5
    scale_angular_turbo:
      yaw: 3.0

    require_enable_button: false
    enable_button: 4  # L2 shoulder button
    enable_turbo_button: 5  # L1 shoulder button